import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers"
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Fetching API",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        {/* <SidebarProvider defaultOpen={defaultOpen}>
          <AppSidebar />
          <main className="md:ml-32">
            <SidebarTrigger /> */}
            {children}
          {/* </main> */}
        {/* </SidebarProvider> */}
      </body>
    </html>
  );
}
